### ISSUE TITLE
ImGui is supposed to be in a root include directory

### ISSUE THREAD

**Issue by Raildex** [CoolLibs/imgui_gradient#1]
I am using CMake for my project together with vcpkg.

Both the ImGui examples themselves aswell the vcpkg port (and any other third party widget i know) expect imgui to be in a root include directory:
`#include <imgui.h>` or
`#include "imgui.h"`.
However, imgui_gradient expects it to be in a subfolder:
`#include <imgui/imgui.h>`.

So if someone uses imgui with vcpkg, using imgui_gradient is impossible without duplicating the headers.

Edit:
```
[build] .../build/.../external/imgui_gradient-src/src/extra_widgets.cpp:2:10: fatal error: 'imgui/imgui.h' file not found
[build] #include <imgui/imgui.h>
[build]          ^~~~~~~~~~~~~~~
[build] 1 error generated.
```

**Comment by JulesFouchy** [comment]
You are right, thanks for the heads up!
