### ISSUE TITLE
Can't drag marks

### ISSUE THREAD

**Issue by Raildex** [CoolLibs/imgui_gradient#2]
I can't drag marks around. I can click on the gradient and it adds marks, but I can't move them around.
I want to have a limited amount of marks (4), so I recreate the gradient on each iteration.
Am I missing something?

```cpp
int point_count = particle_template.color.point_count;
ImGG::GradientWidget gradient_widget{};
//build gradient from existing data
gradient_widget.gradient().clear();
for(int i =0; i < point_count; i++) {
	float4 color = particle_template.color.values[i];
	float pos = particle_template.color.points[i];
	gradient_widget.gradient().add_mark(ImGG::Mark(ImGG::RelativePosition(pos),ImGG::ColorRGBA(color.x,color.y,color.z,color.w)));
}
if(gradient_widget.widget("Color over Lifetime")) {
	auto mark_list = gradient_widget.gradient().get_marks();
	particle_template.color.point_count = std::min(int(mark_list.size()),4);
	auto it = mark_list.begin();
	for(int i =0; i< particle_template.color.point_count; i++,it++) {
		//store gradient in data
		particle_template.color.values[i] = float4(it->color.x,it->color.y,it->color.z,it->color.w);
		particle_template.color.points[i] = it->position.get();
	}
}

```

https://github.com/CoolLibs/imgui_gradient/assets/14938934/65f25a4d-9eef-4315-b3bd-bd49906a3519

**Comment by JulesFouchy** [comment]
Hi ! A `ImGG::GradientWidget` stores internal state and is not meant to be recreated every frame. It is ok to clear it and set data every frame like you do, but you must keep the `ImGG::GradientWidget gradient_widget{};` alive between frames. A quick way to check if this is indeed the problem is to declare it `static` and it should start working.

**Comment by Raildex** [comment]
Thanks! that works. Is there a possibility to make it behave like regular widgets? I mean regular Sliders work without retaining them

**Comment by JulesFouchy** [comment]
> Thanks! that works. Is there a possibility to make it behave like regular widgets? I mean regular Sliders work without retaining them

It would be quite some work, and this is not my priority at all, so this will probably never happen, unless someone is willing to make a PR.
Have a nice day!
