### ISSUE TITLE
IMGUI_DEFINE_MATH_OPERATORS issues

### ISSUE THREAD

**Issue by Raildex** [CoolLibs/imgui_gradient#3]
When linking / compiling with imgui, I receive the error

> Please define IMGUI_DEFINE_MATH_OPERATORS _BEFORE_ including imgui.h

The includes within this project are fairly messy, since imgui.h is included twice or even thrice (Settings.h being one offender).

Cleaning Includes should repair this issue and make it future-proof.

**Comment by JulesFouchy** [comment]
Hi, I think this is fixed (it did fix the issue for me at least). Feel free to reopen it if the problem persists.
