### ISSUE TITLE
Gradient.at(0.0f) sample upper color.

### ISSUE THREAD

**Issue by syoyo** [CoolLibs/imgui_gradient#4]
## Issue

With default GradientWidget configuration(0.0 => black, 1.0 => white)

```
const ColorRGBA color = widget.gradient().at({0.0f});
```

will return the color of white, not black.

This is because the following condition does not become true:

https://github.com/CoolLibs/imgui_gradient/blob/613b0b939a6f0700ce996f4c5c99b4c46f49155d/src/Gradient.cpp#L133

so `lower` is set to nullptr. Then `at` will return upper color here:

https://github.com/CoolLibs/imgui_gradient/blob/613b0b939a6f0700ce996f4c5c99b4c46f49155d/src/Gradient.cpp#L180

## Possible solution

Making the condition of `lower` inclusive may solve the issue.

```
  if (mark.position <= position && (!lower || mark.position >= lower->position))
```

**Comment by JulesFouchy** [comment]
Thanks for the feedback, and the investigation ! This indeed fixes the issue

**Comment by syoyo** [comment]
Awesome! Thank you for the quick fix(and with unit tests!)
