### ISSUE TITLE
Interpolation artifact in GradientBar

### ISSUE THREAD

**Issue by syoyo** [CoolLibs/imgui_gradient#5]
## Step to reproduce

* Setup default GradientWidget
* Move upper marker(white) less than 1.0

https://github.com/user-attachments/assets/6ad348c0-696f-45b8-82d1-12d466c466c3

We can see an artifact(1 pixel-width vertical line), even changing upper color to red, green, etc.

Probably something is not working well in interpolating color.

Confirmed the issue both on Windows and Linux.

**Comment by JulesFouchy** [comment]
Hi, thanks again ;) This is an old issue, I went back on it and found a neat little fix.

**Comment by syoyo** [comment]
Thanks! Confirmed the issue has been fixed!
